# Author: Endri Dibra  

# Project: YOLOv11n RealSense Spatial Object Tracking Pipeline

# Description: Extracting aligned depth and color streams,
# executing computer vision object bounding boxes identification, 
# calculating median workspace distances, and displaying real time telemetry

# Importing Intel RealSense SDK
# to interface with hardware devices
import pyrealsense2 as rs

# Importing numerical python library
# to handle frame matrix conversions
import numpy as np

# Importing open computer vision
# library for rendering image frames
import cv2

# Importing ultralytics framework
# to deploy target object detection
from ultralytics import YOLO

# Importing basic system runtime
# libraries for handling script exits
import sys


# Executing the main function
# to run the spatial tracking
def main():

    print("Loading YOLOv11n model...")

    # Instantiating the neural network
    # model using the tiny network weight file
    model = YOLO("yolo11n.pt")

    # Initializing the hardware pipeline
    # instance to manage stream topologies
    pipeline = rs.pipeline()

    # Initializing stream configuration properties
    config = rs.config()
    
    # Enforcing native high resolution configurations
    # for the incoming 16 bit depth data stream
    config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)

    # Enforcing identical framing dimensions
    # for the companion blue green red color stream
    config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)

    # Verifying network link or pipeline initialization
    try:

        # Activating the data streams
        # matching the enforced structural rules
        profile = pipeline.start(config)

    # Handling camera setup errors
    except Exception as e:

        print(f"Error starting RealSense pipeline: {e}")

        print("Please check if the camera is properly attached via usbipd.")

        # Shutting down runtime execution
        # indicating a failure exit status
        sys.exit(1)

    # Fetching the active device depth processing module
    depth_sensor = profile.get_device().first_depth_sensor()

    # Extracting the multiplier converting
    # raw field data into physical meters
    depth_scale = depth_sensor.get_depth_scale()

    print(f"RealSense depth scale is: {depth_scale}")

    print("YOLOv11n Stream Started. Press 'q' in the window or Ctrl+C in terminal to quit.")

    # Monitoring tracking loops processing
    # safely inside an error handling block
    try:

        # Extracting peripheral frame data packets
        # continuously within an infinite processing loop
        while True:

            # Halting execution flow until
            # a synchronized frame pair arrives
            frames = pipeline.wait_for_frames(5000) 

            # Handling timeout scenarios where
            # the system stops receiving frame feeds
            if not frames:

                print("Timeout: No frames received from camera.")

                # Restarting the extraction cycle
                continue

            # Isolating the specialized depth
            # component frame from the bundle
            depth_frame = frames.get_depth_frame()

            # Isolating the standard color
            # texture component from the bundle
            color_frame = frames.get_color_frame()

            # Dropping processing steps if
            # either target stream asset is missing
            if not depth_frame or not color_frame:

                print("Missing depth or color frame.")

                # Restarting the extraction cycle
                continue

            # Transforming raw depth array
            # chunks into readable multidimensional arrays
            depth_image = np.asanyarray(depth_frame.get_data())

            # Transforming color texture buffers
            # into standard image matrix representations
            color_image = np.asanyarray(color_frame.get_data())

            # Evaluating the incoming frame
            # tracking objects using streaming generation
            results = model(color_image, stream=True, verbose=False)

            # Flagging tracking status flags
            # before parsing detected bounding boxes
            detected_something = False

            # Looping over spatial tensors
            # generated by the deep neural network
            for result in results:

                # Isolating structural data containing bounding shapes
                boxes = result.boxes

                # Iterating over individual items
                # located inside the single frame results
                for box in boxes:

                    # Extracting integer pixels defining bounding shapes
                    x1, y1, x2, y2 = map(int, box.xyxy[0])

                    # Extracting probability parameters tracking confidence
                    confidence = float(box.conf[0])

                    # Extracting identifier integers mapping class names
                    class_id = int(box.cls[0])

                    # Resolving vocabulary definitions matching class hashes
                    label = model.names[class_id]

                    # Filtering weak classifications out
                    # before assessing spatial depth placement
                    if confidence < 0.5:
                        continue

                    # Pinpointing center coordinate pixels
                    cx = np.clip((x1 + x2) // 2, 0, depth_image.shape[1] - 1)

                    # Pinpointing center coordinate pixels
                    cy = np.clip((y1 + y2) // 2, 0, depth_image.shape[0] - 1)
                    
                    # Setting spatial filtering window bounds
                    patch_size = 2

                    # Determining row selection starting points
                    y_start = max(0, cy - patch_size)

                    # Determining row selection terminal bounds
                    y_end = min(depth_image.shape[0], cy + patch_size + 1)

                    # Determining column selection starting points
                    x_start = max(0, cx - patch_size)

                    # Determining column selection terminal bounds
                    x_end = min(depth_image.shape[1], cx + patch_size + 1)

                    # Slicing the structural matrix
                    # gathering small window pixel matrices
                    depth_patch = depth_image[y_start:y_end, x_start:x_end]

                    # Stripping out invalid pixels
                    # matching zero measurements
                    valid_depths = depth_patch[depth_patch > 0]

                    # Checking structural status layers
                    if len(valid_depths) > 0:

                        # Extracting central values avoiding pixel anomalies
                        median_raw_depth = np.median(valid_depths)

                        # Scaling data values out into absolute distance metrics
                        distance_meters = median_raw_depth * depth_scale

                    # Handling missing distance calculations
                    else:

                        # Assigning default indicators representing blindspots
                        distance_meters = -1.0

                    # Rejecting spatial points lying outside our workspace
                    if distance_meters <= 0 or distance_meters > 1.0:
                        continue

                    # Activating display flag variables
                    detected_something = True

                    print(f"[DETECTED] {label} | Conf: {confidence:.2f} | Dist: {distance_meters:.3f}m")

                    # Outlining targets using colored bounding rectangles
                    cv2.rectangle(color_image, (x1, y1), (x2, y2), (0, 255, 0), 2)

                    # Marking spatial target centers with solid color points
                    cv2.circle(color_image, (cx, cy), 5, (0, 0, 255), -1)

                    # Compiling metric information into target display headers
                    info_text = f"{label} {confidence:.2f} | Dist: {distance_meters:.3f}m"

                    # Writing tracking telemetry strings onto target frames
                    cv2.putText(color_image, info_text, (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

            # Notifying terminal consoles when no objects are detected
            if not detected_something:

                print("Streaming... No target objects tracking within reach.", end="\r")

            # Mapping the scaled raw matrix
            # into a visual pseudo color heatmap
            depth_colormap = cv2.applyColorMap(cv2.convertScaleAbs(depth_image, alpha=0.05), cv2.COLORMAP_JET)

            # Concatenating color and depth matrices
            # side by side into an aggregate display element
            output_window = np.hstack((color_image, depth_colormap))
            
            # Verifying open graphic user interface stability
            try:

                # Pushing the aggregate display element
                # directly onto an interactive user interface panel
                cv2.imshow("YOLOv11n RealSense Tracking", output_window)

                # Sampling keyboard interrupts every millisecond
                if cv2.waitKey(1) & 0xFF == ord('q'):

                    # Terminating the processing loops
                    # to trigger hardware resource teardown
                    break

            # Catching dynamic visual window rendering faults
            except Exception as gui_error:
                pass

    # Handling abrupt terminal exit signaling
    except KeyboardInterrupt:

        print("\nStream stopped by user via terminal.")

    # Releasing physical assets cleanly
    # regardless of execution termination status
    finally:

        # Deactivating camera data streams
        # and freeing internal sensor pipelines
        pipeline.stop()

        # Closing interface panel display blocks
        # to release windows desktop resources
        cv2.destroyAllWindows()


# Direct script execution
if __name__ == "__main__":

    # Invoking the main function
    main()
